[[streams]]
city   = "Varied"
label  = "yo"
link   = "https://twitch.tv/woke"
notes  = "Live protest streams from around the world."
source = "woke.net"

[[streams]]
kind  = "web"
label = "zombocom"
link  = "https://devash-testbench2.herokuapp.com"
